import { Geist, Geist_Mono, Assistant } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import GlobalStoreProvider from "../components/Application/GlobalStoreProvider";


const geistSans = Assistant({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased`}
      >
        <GlobalStoreProvider>
          <ToastContainer/>
          {children}
        </GlobalStoreProvider>
      </body>
    </html>
  );
}
