import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div className="h-screen w-screen flex justify-center items-center">
        {children}
    </div>
  );
}
